# NumPy

In [1]:
####################### Numpy ##############################

import numpy as np

arreglo_normal = [1, 2 ,3 ,4 ,5 ,6 ,7 ,9 ,10 ]
print(arreglo_normal)
print(type(arreglo_normal))

arreglo_numpy = np.array([1,2,3,4,5,6,7,8,9,10])
print(arreglo_numpy)
print(type(arreglo_numpy))


[1, 2, 3, 4, 5, 6, 7, 9, 10]
<class 'list'>
[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


In [2]:
########### arreglo de una dimensión ##############

print('########### arreglo de una dimensión ##############')
arr_una_dim = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr_una_dim)
print(arr_una_dim[0])

########### arreglo de dos dimensiones ##############

print("########### arreglo de dos dimensiones ##############")
arr_dos_dim = np.array([[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20]])
print(arr_dos_dim)
print(arr_dos_dim[1][0])
print(arr_dos_dim[0,0])

########### arreglo de tres dimensiones ##############

print('########### arreglo de tres dimensiones ##############')
arr_tres_dim = np.array([[[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20]],
[[21,22,23,24,25,26,27,28,29,30],[31,32,33,34,35,36,37,38,39,40]]])
print(arr_tres_dim)
print(arr_tres_dim[1,0,0])
print(arr_tres_dim[1][0][0])

########### arreglo de una dimensión ##############
[ 1  2  3  4  5  6  7  8  9 10]
1
########### arreglo de dos dimensiones ##############
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
11
1
########### arreglo de tres dimensiones ##############
[[[ 1  2  3  4  5  6  7  8  9 10]
  [11 12 13 14 15 16 17 18 19 20]]

 [[21 22 23 24 25 26 27 28 29 30]
  [31 32 33 34 35 36 37 38 39 40]]]
21
21


In [3]:
########################## índice negativo ##########################

# viendo el ultimo elemento del arr_una_dim
print('########## indice negativo en una dimensión ##########')
print(arr_una_dim[-1])


# viendo el primer elemento de la ultima fila del arr_dos_dim
print('########## indice negativo en dos dimensiones ##########')
print(arr_dos_dim[-1,0])
print(arr_dos_dim[-1,-1])


# viendo el primer elemento del segundo vertice en la ultima fila del arr_tres_dim
print('########## indice negativo en tres dimensiones ##########')
print(arr_tres_dim[-1,1,0])
print(arr_tres_dim[-1,0,-5])

########## indice negativo en una dimensión ##########
10
########## indice negativo en dos dimensiones ##########
11
20
########## indice negativo en tres dimensiones ##########
31
26


In [7]:
########################## rangos ##########################

# recorriendo del 1 al 5 del arr_una_dim
print('########## rangos en una dimensión ##########')
print(arr_una_dim[0:5])
print(arr_una_dim[4:10])

########################## rangos con pasos ##########################
print('########## rangos con pasos en una dimensión ##########')
print(arr_una_dim[0:10:2])
print(arr_una_dim[0:10:3])


########## rangos en una dimensión ##########
[1 2 3 4 5]
====> [1]
[ 5  6  7  8  9 10]
########## rangos con pasos en una dimensión ##########
[1 3 5 7 9]
[ 1  4  7 10]


In [10]:
########################## recorriendo con rangos sin inicio ##########################
print('########## recorriendo con rangos sin inicio en una dimensión ##########')
print(arr_una_dim[:5])

########################## recorriendo con rangos sin fin ##########################
print('########## recorriendo con rangos sin fin en una dimensión ##########')
print(arr_una_dim[5:])

########################## recorriendo con rangos sin inicio y sin fin ##########################
print('########## recorriendo con rangos sin inicio y sin fin en una dimensión ##########')
print(arr_una_dim[:])


########################## recorriendo con rangos negativos ##########################
print('########## recorriendo con rangos negativos en una dimensión ##########')
print(arr_una_dim[-5:-1])
print(arr_una_dim[-5:])
print(arr_una_dim[-1:])

########## recorriendo con rangos sin inicio en una dimensión ##########
[1 2 3 4 5]
########## recorriendo con rangos sin fin en una dimensión ##########
[ 6  7  8  9 10]
########## recorriendo con rangos sin inicio y sin fin en una dimensión ##########
[ 1  2  3  4  5  6  7  8  9 10]
########## recorriendo con rangos negativos en una dimensión ##########
[6 7 8 9]
[ 6  7  8  9 10]
[10]


In [14]:
# Shape en una dimensión
print(arr_una_dim.shape)

# Shape en dos dimensiones
print(arr_dos_dim.shape)

# Shape en tres dimensiones
print(arr_tres_dim.shape)

(10,)
(2, 10)
(2, 2, 10)


In [25]:
# reshape en una dimensión
print('reshape de 5,2')
resha_arr_una_dim = arr_una_dim.reshape(5,2)
print(resha_arr_una_dim)

print('reshape de 2,5')
resha_arr_una_dim = arr_una_dim.reshape(2,5)
print(resha_arr_una_dim)

# reshape en dos dimensiones
print('reshape de 2,5,2')
resha_arr_dos_dim = arr_dos_dim.reshape(2,5,2)
print(resha_arr_dos_dim)

# reshape en tres dimensiones
print('reshape de 2,5,2,2')
resha_arr_tres_dim = arr_tres_dim.reshape(2,5,2,2)
print(resha_arr_tres_dim)



reshape de 5,2
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
reshape de 2,5
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
reshape de 2,5,2
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]
  [15 16]
  [17 18]
  [19 20]]]
reshape de 2,5,2,2


ValueError: cannot reshape array of size 40 into shape (2,5,2,3)