# NumPy

In [31]:
import numpy as np
import time

In [1]:
####################### Numpy ##############################

arreglo_normal = [1, 2 ,3 ,4 ,5 ,6 ,7 ,9 ,10 ]
print(arreglo_normal)
print(type(arreglo_normal))

arreglo_numpy = np.array([1,2,3,4,5,6,7,8,9,10])
print(arreglo_numpy)
print(type(arreglo_numpy))


[1, 2, 3, 4, 5, 6, 7, 9, 10]
<class 'list'>
[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


In [2]:
########### arreglo de una dimensión ##############

print('########### arreglo de una dimensión ##############')
arr_una_dim = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr_una_dim)
print(arr_una_dim[0])

########### arreglo de dos dimensiones ##############

print("########### arreglo de dos dimensiones ##############")
arr_dos_dim = np.array([[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20]])
print(arr_dos_dim)
print(arr_dos_dim[1][0])
print(arr_dos_dim[0,0])

########### arreglo de tres dimensiones ##############

print('########### arreglo de tres dimensiones ##############')
arr_tres_dim = np.array([[[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20]],
[[21,22,23,24,25,26,27,28,29,30],[31,32,33,34,35,36,37,38,39,40]]])
print(arr_tres_dim)
print(arr_tres_dim[1,0,0])
print(arr_tres_dim[1][0][0])

########### arreglo de una dimensión ##############
[ 1  2  3  4  5  6  7  8  9 10]
1
########### arreglo de dos dimensiones ##############
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
11
1
########### arreglo de tres dimensiones ##############
[[[ 1  2  3  4  5  6  7  8  9 10]
  [11 12 13 14 15 16 17 18 19 20]]

 [[21 22 23 24 25 26 27 28 29 30]
  [31 32 33 34 35 36 37 38 39 40]]]
21
21


In [3]:
########################## índice negativo ##########################

# viendo el ultimo elemento del arr_una_dim
print('########## indice negativo en una dimensión ##########')
print(arr_una_dim[-1])


# viendo el primer elemento de la ultima fila del arr_dos_dim
print('########## indice negativo en dos dimensiones ##########')
print(arr_dos_dim[-1,0])
print(arr_dos_dim[-1,-1])


# viendo el primer elemento del segundo vertice en la ultima fila del arr_tres_dim
print('########## indice negativo en tres dimensiones ##########')
print(arr_tres_dim[-1,1,0])
print(arr_tres_dim[-1,0,-5])

########## indice negativo en una dimensión ##########
10
########## indice negativo en dos dimensiones ##########
11
20
########## indice negativo en tres dimensiones ##########
31
26


In [7]:
########################## rangos ##########################

# recorriendo del 1 al 5 del arr_una_dim
print('########## rangos en una dimensión ##########')
print(arr_una_dim[0:5])
print(arr_una_dim[4:10])

########################## rangos con pasos ##########################
print('########## rangos con pasos en una dimensión ##########')
print(arr_una_dim[0:10:2])
print(arr_una_dim[0:10:3])


########## rangos en una dimensión ##########
[1 2 3 4 5]
====> [1]
[ 5  6  7  8  9 10]
########## rangos con pasos en una dimensión ##########
[1 3 5 7 9]
[ 1  4  7 10]


In [10]:
########################## recorriendo con rangos sin inicio ##########################
print('########## recorriendo con rangos sin inicio en una dimensión ##########')
print(arr_una_dim[:5])

########################## recorriendo con rangos sin fin ##########################
print('########## recorriendo con rangos sin fin en una dimensión ##########')
print(arr_una_dim[5:])

########################## recorriendo con rangos sin inicio y sin fin ##########################
print('########## recorriendo con rangos sin inicio y sin fin en una dimensión ##########')
print(arr_una_dim[:])


########################## recorriendo con rangos negativos ##########################
print('########## recorriendo con rangos negativos en una dimensión ##########')
print(arr_una_dim[-5:-1])
print(arr_una_dim[-5:])
print(arr_una_dim[-1:])

########## recorriendo con rangos sin inicio en una dimensión ##########
[1 2 3 4 5]
########## recorriendo con rangos sin fin en una dimensión ##########
[ 6  7  8  9 10]
########## recorriendo con rangos sin inicio y sin fin en una dimensión ##########
[ 1  2  3  4  5  6  7  8  9 10]
########## recorriendo con rangos negativos en una dimensión ##########
[6 7 8 9]
[ 6  7  8  9 10]
[10]


In [14]:
# Shape en una dimensión
print(arr_una_dim.shape)

# Shape en dos dimensiones
print(arr_dos_dim.shape)

# Shape en tres dimensiones
print(arr_tres_dim.shape)

(10,)
(2, 10)
(2, 2, 10)


In [26]:
# reshape en una dimensión
print('reshape de 5,2')
resha_arr_una_dim = arr_una_dim.reshape(5,2)
print(resha_arr_una_dim)

print('reshape de 2,5')
resha_arr_una_dim = arr_una_dim.reshape(2,5)
print(resha_arr_una_dim)

# reshape en dos dimensiones
print('reshape de 2,5,2')
resha_arr_dos_dim = arr_dos_dim.reshape(2,5,2)
print(resha_arr_dos_dim)

# reshape en tres dimensiones
print('reshape de 2,5,2,2')
resha_arr_tres_dim = arr_tres_dim.reshape(2,5,2,2)
print(resha_arr_tres_dim)



reshape de 5,2
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
reshape de 2,5
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
reshape de 2,5,2
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]
  [15 16]
  [17 18]
  [19 20]]]
reshape de 2,5,2,2
[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]

  [[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]

  [[17 18]
   [19 20]]]


 [[[21 22]
   [23 24]]

  [[25 26]
   [27 28]]

  [[29 30]
   [31 32]]

  [[33 34]
   [35 36]]

  [[37 38]
   [39 40]]]]


In [30]:
# reshape con el comodin -1
print('reshape con el comodin -1,2')
print(arr_una_dim.shape)
resha_arr_una_dim_comodin = arr_una_dim.reshape(-1,2)
print(resha_arr_una_dim_comodin.shape)

# Volviendo a una dimensión
print('volviendo a una dimensión')
print(resha_arr_tres_dim.shape)
print(resha_arr_tres_dim.reshape(-1).shape)


reshape con el comodin -1,2
(10,)
(5, 2)
volviendo a una dimensión
(2, 5, 2, 2)
(40,)


In [36]:
# iterando una dimension con un for
print('iterando una dimension con un for')
for dato in arr_una_dim:
    print('viendo el dato: {} {}'.format(dato,type(dato)))
    time.sleep(1)


iterando una dimension con un for
viendo el dato: 1 <class 'numpy.int64'>
viendo el dato: 2 <class 'numpy.int64'>
viendo el dato: 3 <class 'numpy.int64'>
viendo el dato: 4 <class 'numpy.int64'>
viendo el dato: 5 <class 'numpy.int64'>
viendo el dato: 6 <class 'numpy.int64'>
viendo el dato: 7 <class 'numpy.int64'>
viendo el dato: 8 <class 'numpy.int64'>
viendo el dato: 9 <class 'numpy.int64'>
viendo el dato: 10 <class 'numpy.int64'>


In [41]:
# iterando dos dimensiones con un for
print('iterando dos dimensiones con un for')
print(arr_dos_dim.shape)
print(arr_dos_dim)
for fila in arr_dos_dim:
    print('viendo la fila: {} {}'.format(fila,type(fila)))
    for columna in fila:
        print('viendo la columna: {} {}'.format(columna,type(columna)))
        # time.sleep(1)


iterando dos dimensiones con un for
(2, 10)
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
viendo la fila: [ 1  2  3  4  5  6  7  8  9 10] <class 'numpy.ndarray'>
viendo la columna: 1 <class 'numpy.int64'>
viendo la columna: 2 <class 'numpy.int64'>
viendo la columna: 3 <class 'numpy.int64'>
viendo la columna: 4 <class 'numpy.int64'>
viendo la columna: 5 <class 'numpy.int64'>
viendo la columna: 6 <class 'numpy.int64'>
viendo la columna: 7 <class 'numpy.int64'>
viendo la columna: 8 <class 'numpy.int64'>
viendo la columna: 9 <class 'numpy.int64'>
viendo la columna: 10 <class 'numpy.int64'>
viendo la fila: [11 12 13 14 15 16 17 18 19 20] <class 'numpy.ndarray'>
viendo la columna: 11 <class 'numpy.int64'>
viendo la columna: 12 <class 'numpy.int64'>
viendo la columna: 13 <class 'numpy.int64'>
viendo la columna: 14 <class 'numpy.int64'>
viendo la columna: 15 <class 'numpy.int64'>
viendo la columna: 16 <class 'numpy.int64'>
viendo la columna: 17 <class 'numpy.int64'>
viendo

In [43]:
# iterando tres dimensiones con un for
print('iterando tres dimensiones con un for')
print(arr_tres_dim.shape)
print(arr_tres_dim)
for fila in arr_tres_dim:
    print('viendo la fila: {} {}'.format(fila,type(fila)))
    for columna in fila:
        print('viendo la columna: {} {}'.format(columna,type(columna)))
        for vertice in columna:
            print('viendo el vertice: {} {}'.format(vertice,type(vertice)))
            time.sleep(0.2)

iterando tres dimensiones con un for
(2, 2, 10)
[[[ 1  2  3  4  5  6  7  8  9 10]
  [11 12 13 14 15 16 17 18 19 20]]

 [[21 22 23 24 25 26 27 28 29 30]
  [31 32 33 34 35 36 37 38 39 40]]]
viendo la fila: [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]] <class 'numpy.ndarray'>
viendo la columna: [ 1  2  3  4  5  6  7  8  9 10] <class 'numpy.ndarray'>
viendo el vertice: 1 <class 'numpy.int64'>
viendo el vertice: 2 <class 'numpy.int64'>
viendo el vertice: 3 <class 'numpy.int64'>
viendo el vertice: 4 <class 'numpy.int64'>
viendo el vertice: 5 <class 'numpy.int64'>
viendo el vertice: 6 <class 'numpy.int64'>
viendo el vertice: 7 <class 'numpy.int64'>
viendo el vertice: 8 <class 'numpy.int64'>
viendo el vertice: 9 <class 'numpy.int64'>
viendo el vertice: 10 <class 'numpy.int64'>
viendo la columna: [11 12 13 14 15 16 17 18 19 20] <class 'numpy.ndarray'>
viendo el vertice: 11 <class 'numpy.int64'>
viendo el vertice: 12 <class 'numpy.int64'>
viendo el vertice: 13 <class 'numpy.

In [45]:
# iterando una dimension con for cambiando el shape
print('iterando una dimension con for cambiando el shape')
print(arr_tres_dim.shape)
print(arr_tres_dim)
for dato in arr_tres_dim.reshape(-1):
    print('viendo el dato: {} {}'.format(dato,type(dato)))
    time.sleep(0.5)

iterando una dimension con for cambiando el shape
(2, 2, 10)
[[[ 1  2  3  4  5  6  7  8  9 10]
  [11 12 13 14 15 16 17 18 19 20]]

 [[21 22 23 24 25 26 27 28 29 30]
  [31 32 33 34 35 36 37 38 39 40]]]
viendo el dato: 1 <class 'numpy.int64'>
viendo el dato: 2 <class 'numpy.int64'>
viendo el dato: 3 <class 'numpy.int64'>
viendo el dato: 4 <class 'numpy.int64'>
viendo el dato: 5 <class 'numpy.int64'>
viendo el dato: 6 <class 'numpy.int64'>
viendo el dato: 7 <class 'numpy.int64'>
viendo el dato: 8 <class 'numpy.int64'>
viendo el dato: 9 <class 'numpy.int64'>
viendo el dato: 10 <class 'numpy.int64'>
viendo el dato: 11 <class 'numpy.int64'>
viendo el dato: 12 <class 'numpy.int64'>
viendo el dato: 13 <class 'numpy.int64'>
viendo el dato: 14 <class 'numpy.int64'>
viendo el dato: 15 <class 'numpy.int64'>
viendo el dato: 16 <class 'numpy.int64'>
viendo el dato: 17 <class 'numpy.int64'>
viendo el dato: 18 <class 'numpy.int64'>
viendo el dato: 19 <class 'numpy.int64'>
viendo el dato: 20 <class 'nu

In [46]:
# iterando con nditer
print('iterando con nditer')
print(arr_tres_dim.shape)
print(arr_tres_dim)
for dato in np.nditer(arr_tres_dim):
    print('viendo el dato: {} {}'.format(dato,type(dato)))
    time.sleep(0.5)

iterando con nditer
(2, 2, 10)
[[[ 1  2  3  4  5  6  7  8  9 10]
  [11 12 13 14 15 16 17 18 19 20]]

 [[21 22 23 24 25 26 27 28 29 30]
  [31 32 33 34 35 36 37 38 39 40]]]
viendo el dato: 1 <class 'numpy.ndarray'>
viendo el dato: 2 <class 'numpy.ndarray'>
viendo el dato: 3 <class 'numpy.ndarray'>
viendo el dato: 4 <class 'numpy.ndarray'>
viendo el dato: 5 <class 'numpy.ndarray'>
viendo el dato: 6 <class 'numpy.ndarray'>
viendo el dato: 7 <class 'numpy.ndarray'>
viendo el dato: 8 <class 'numpy.ndarray'>
viendo el dato: 9 <class 'numpy.ndarray'>
viendo el dato: 10 <class 'numpy.ndarray'>
viendo el dato: 11 <class 'numpy.ndarray'>
viendo el dato: 12 <class 'numpy.ndarray'>
viendo el dato: 13 <class 'numpy.ndarray'>
viendo el dato: 14 <class 'numpy.ndarray'>
viendo el dato: 15 <class 'numpy.ndarray'>
viendo el dato: 16 <class 'numpy.ndarray'>
viendo el dato: 17 <class 'numpy.ndarray'>
viendo el dato: 18 <class 'numpy.ndarray'>
viendo el dato: 19 <class 'numpy.ndarray'>
viendo el dato: 20 <c

In [48]:
# iterando dos dimensiones con ednumerate
print('iterando dos dimensiones con ednumerate')
print(arr_dos_dim.shape)
print(arr_dos_dim)
for indice,dato in np.ndenumerate(arr_dos_dim):
    print('∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞')
    print('viendo el indice: {} {}'.format(indice,type(indice)))
    print('viendo el dato: {} {}'.format(dato,type(dato)))
    time.sleep(0.5)

iterando con ednumerate
(2, 10)
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞
viendo el indice: (0, 0) <class 'tuple'>
viendo el dato: 1 <class 'numpy.int64'>
∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞
viendo el indice: (0, 1) <class 'tuple'>
viendo el dato: 2 <class 'numpy.int64'>
∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞
viendo el indice: (0, 2) <class 'tuple'>
viendo el dato: 3 <class 'numpy.int64'>
∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞
viendo el indice: (0, 3) <class 'tuple'>
viendo el dato: 4 <class 'numpy.int64'>
∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞
viendo el indice: (0, 4) <class 'tuple'>
viendo el dato: 5 <class 'numpy.int64'>
∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞
viendo el indice: (0, 5) <class 'tuple'>
viendo el dato: 6 <class 'numpy.int64'>
∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞
viendo el indice: (0, 6) <class 'tuple'>
vie

In [50]:
# iterando tres dimensiones con ednumerate
print('iterando tres dimensiones con ednumerate')
print(arr_tres_dim.shape)
print(arr_tres_dim)
for indice,dato in np.ndenumerate(arr_tres_dim):
    print('∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞')
    print('viendo el indice: {} {}'.format(indice,type(indice)))
    print('viendo el dato: {} {}'.format(dato,type(dato)))
    time.sleep(0.5)

iterando tres dimensiones con ednumerate
(2, 2, 10)
[[[ 1  2  3  4  5  6  7  8  9 10]
  [11 12 13 14 15 16 17 18 19 20]]

 [[21 22 23 24 25 26 27 28 29 30]
  [31 32 33 34 35 36 37 38 39 40]]]
∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞
viendo el indice: (0, 0, 0) <class 'tuple'>
viendo el dato: 1 <class 'numpy.int64'>
∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞
viendo el indice: (0, 0, 1) <class 'tuple'>
viendo el dato: 2 <class 'numpy.int64'>
∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞
viendo el indice: (0, 0, 2) <class 'tuple'>
viendo el dato: 3 <class 'numpy.int64'>
∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞
viendo el indice: (0, 0, 3) <class 'tuple'>
viendo el dato: 4 <class 'numpy.int64'>
∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞
viendo el indice: (0, 0, 4) <class 'tuple'>
viendo el dato: 5 <class 'numpy.int64'>
∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞
viendo el indice: (0, 0, 5) <class 'tuple'>
viendo el dato: 6 <class '

In [52]:
# concatenando nparreglos
arreglo_uno = np.array([91,82,33,74,92])
arreglo_dos = np.array([12,13,45,34,63])

arreglo_concatenado = np.concatenate((arreglo_uno,arreglo_dos))
print(arreglo_concatenado)

[91 82 33 74 92 12 13 45 34 63]


In [56]:
# concatenando nparreglos con axis = 0
arreglo_concatenado = np.concatenate((arreglo_uno,arreglo_dos),axis=0)
print(arreglo_concatenado)

[91 82 33 74 92 12 13 45 34 63]


In [71]:
# concatenando nparreglos con axis = 0
arreglo_dos_dim_uno = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('shape de arreglo_dos_dim_uno: {}'.format(arreglo_dos_dim_uno.shape))
arreglo_dos_dim_dos = np.array([[11,12,13,14,15],[16,17,18,19,20]])
print('shape de arreglo_dos_dim_dos: {}'.format(arreglo_dos_dim_dos.shape))

arreglo_concat_axis0 = np.concatenate((arreglo_dos_dim_uno,arreglo_dos_dim_dos),axis=0)
print(arreglo_concat_axis0)
print(arreglo_concat_axis0.shape)

print('∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞')
# concatenando nparreglos con axis = 1
arreglo_concat_axis1 = np.concatenate((arreglo_dos_dim_uno,arreglo_dos_dim_dos),axis=1)
#print(arreglo_concat_axis1)
print(arreglo_concat_axis1.shape)


# haciendo reshape para pasar a 5 dimensiones
arr_cinco_dim_uno = arreglo_dos_dim_uno.reshape(1,1,5,2,1)
print(arr_cinco_dim_uno)
print(arr_cinco_dim_uno.shape)
arr_cinco_dim_dos = arreglo_dos_dim_dos.reshape(1,1,5,2,1)
print(arr_cinco_dim_dos.shape)

# concatenando nparreglos con axis = 4
arreglo_concat_axis4 = np.concatenate((arr_cinco_dim_uno,arr_cinco_dim_dos),axis=4)
print(arreglo_concat_axis4)
print(arreglo_concat_axis4.shape)


shape de arreglo_dos_dim_uno: (2, 5)
shape de arreglo_dos_dim_dos: (2, 5)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
(4, 5)
∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞
(2, 10)
[[[[[ 1]
    [ 2]]

   [[ 3]
    [ 4]]

   [[ 5]
    [ 6]]

   [[ 7]
    [ 8]]

   [[ 9]
    [10]]]]]
(1, 1, 5, 2, 1)
(1, 1, 5, 2, 1)
[[[[[ 1 11]
    [ 2 12]]

   [[ 3 13]
    [ 4 14]]

   [[ 5 15]
    [ 6 16]]

   [[ 7 17]
    [ 8 18]]

   [[ 9 19]
    [10 20]]]]]
(1, 1, 5, 2, 2)


In [81]:
# uniendo nparreglos con np.stack
print('shape de arreglo_dos_dim_uno: {}'.format(arreglo_dos_dim_uno.shape))
print('shape de arreglo_dos_dim_dos: {}'.format(arreglo_dos_dim_dos.shape))
print('el shape de union con concatenate axis = 0: {}'.format(arreglo_concat_axis0.shape))

# uniendo nparreglos con np.stack axis = 0
arreglo_stack_axis0 = np.stack((arreglo_dos_dim_uno,arreglo_dos_dim_dos),axis=0)
print(arreglo_stack_axis0)
print(arreglo_stack_axis0.shape)

# uniendo nparreglos con np.stack axis = 1
arreglo_stack_axis1 = np.stack((arreglo_dos_dim_uno,arreglo_dos_dim_dos),axis=1)
print(arreglo_stack_axis1)
print(arreglo_stack_axis1.shape)

# uniendo nparreglos con np.stack axis = 2
arreglo_stack_axis2 = np.stack((arreglo_dos_dim_uno,arreglo_dos_dim_dos),axis=2)
print(arreglo_stack_axis2)
print(arreglo_stack_axis2.shape)

shape de arreglo_dos_dim_uno: (2, 5)
shape de arreglo_dos_dim_dos: (2, 5)
el shape de union con concatenate axis = 0: (4, 5)
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
(2, 2, 5)
[[[ 1  2  3  4  5]
  [11 12 13 14 15]]

 [[ 6  7  8  9 10]
  [16 17 18 19 20]]]
(2, 2, 5)
[[[ 1 11]
  [ 2 12]
  [ 3 13]
  [ 4 14]
  [ 5 15]]

 [[ 6 16]
  [ 7 17]
  [ 8 18]
  [ 9 19]
  [10 20]]]
(2, 5, 2)


In [82]:
# uniendo nparreglos con np.hstack
arreglo_hstack = np.hstack((arreglo_dos_dim_uno,arreglo_dos_dim_dos))
print(arreglo_hstack)
print(arreglo_hstack.shape)

# uniendo nparreglos con np.vstack
arreglo_vstack = np.vstack((arreglo_dos_dim_uno,arreglo_dos_dim_dos))
print(arreglo_vstack)
print(arreglo_vstack.shape)

[[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9 10 16 17 18 19 20]]
(2, 10)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
(4, 5)


In [85]:
# operaciones algebraicas de numeros enteros con los nparreglos
print('operaciones algebraicas de numeros enteros con los nparreglos')
print('arreglo base')
print(arreglo_vstack)

print('arreglo_vstack + 2')
print(arreglo_vstack+2)

print('arreglo_vstack - 2')
print(arreglo_vstack-2)

print('arreglo_vstack * 2')
print(arreglo_vstack*2)

operaciones algebraicas de numeros enteros con los nparreglos
arreglo base
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
arreglo_vstack + 2
[[ 3  4  5  6  7]
 [ 8  9 10 11 12]
 [13 14 15 16 17]
 [18 19 20 21 22]]
arreglo_vstack - 2
[[-1  0  1  2  3]
 [ 4  5  6  7  8]
 [ 9 10 11 12 13]
 [14 15 16 17 18]]
arreglo_vstack * 2
[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]]


In [93]:
# aprendiendo a usar el where
print('aprendiendo a usar el where')

arreglo = np.array([87,12,37,81,34,91,41,29,81,98])

resultado_busqueda = np.where(arreglo>=81)
print(resultado_busqueda)

print('corroborando el resultado de la busqueda')
print(arreglo[resultado_busqueda])



aprendiendo a usar el where
(array([0, 3, 5, 8, 9]),)
corroborando el resultado de la busqueda
[87 81 91 81 98]


In [94]:
# buscando todos los elementos que son multiplos de 3 en arreglo
print('buscando todos los elementos que son multiplos de 3 en arreglo')
arreglo_multiplos_tres = np.where(arreglo%3==0)
print(arreglo_multiplos_tres)

print('corroborando el resultado de la busqueda')
print(arreglo[arreglo_multiplos_tres])

buscando todos los elementos que son multiplos de 3 en arreglo
(array([0, 1, 3, 8]),)
corroborando el resultado de la busqueda
[87 12 81 81]


In [95]:
# ordenando los elementos de un arreglo
print('ordenando los elementos de un arreglo')
arreglo = np.array(['el','niño','se','cambio','de','casa','porque','no','le','gustaba','la','suya'])
print(arreglo)

arreglo_ordenado = np.sort(arreglo)
print(arreglo_ordenado)

ordenando los elementos de un arreglo
['el' 'niño' 'se' 'cambio' 'de' 'casa' 'porque' 'no' 'le' 'gustaba' 'la'
 'suya']
['cambio' 'casa' 'de' 'el' 'gustaba' 'la' 'le' 'niño' 'no' 'porque' 'se'
 'suya']


In [98]:
# realizando una busqueda con for
arreglo = np.array(['el','niño','se','cambio','de','casa','porque','no','le','gustaba','la','suya'])

filtro = []

for dato in arreglo:
    if dato.find('e') != -1:
        filtro.append(True)
    elif dato.find('o') != -1:
        filtro.append(True)
    else:
        filtro.append(False)

print(filtro)

resultado_filtro = arreglo[filtro]
print(resultado_filtro)


[True, True, True, True, True, False, True, True, True, False, False, False]
['el' 'niño' 'se' 'cambio' 'de' 'porque' 'no' 'le']


In [102]:
# realizando filtro simple
print('realizando filtro simple')

arreglo = np.array([87,12,37,81,34,91,41,29,81,98])

filtro = arreglo >= 81

print(filtro)

arreglo_filtrado = arreglo[filtro]
print(arreglo_filtrado)

realizando filtro simple
[ True False False  True False  True False False  True  True]
[87 81 91 81 98]


In [111]:
# operaciones algebraicas entre nparreglos
print('operaciones algebraicas entre nparreglos')

arr_uno = np.array([91,82,33,74,92])
arr_dos = np.array([1,2,3,4,5])

print('suma entre arr_uno y arr_dos')
print(np.add(arr_uno,arr_dos))

print('resta entre arr_uno y arr_dos')
print(np.subtract(arr_uno,arr_dos))

print('multiplicacion entre arr_uno y arr_dos')
print(np.multiply(arr_uno,arr_dos))

print('division entre arr_uno y arr_dos')
print(np.divide(arr_uno,arr_dos))

print('divmod entre arr_uno y arr_dos')
print(np.divmod(arr_uno,arr_dos)[0])
print(np.divmod(arr_uno,arr_dos)[1])

operaciones algebraicas entre nparreglos
suma entre arr_uno y arr_dos
[92 84 36 78 97]
resta entre arr_uno y arr_dos
[90 80 30 70 87]
multiplicacion entre arr_uno y arr_dos
[ 91 164  99 296 460]
division entre arr_uno y arr_dos
[91.  41.  11.  18.5 18.4]
divmod entre arr_uno y arr_dos
[91 41 11 18 18]
[0 0 0 2 2]
